### ISSUE TITLE
static filed in class init

### ISSUE THREAD

**Issue by BaskDuan** [blipinsk/app-startup-hilt-sample#1]
hilt should have an entry point, 
but if entry is UI component , writen in xml ,maybe can't add an entry point
add init function at  static filed in class could be another thinking ?

**Comment by blipinsk** [comment]
Hi DuanTzXavier, 
I'm sorry but I don't think I understand your question. Could you provide a piece of sample code so that we can get on the same page?

**Comment by BaskDuan** [comment]
```
class AInitializer: Initializer<A> {

    override fun create(context: Context): A {
        A.init()
        return A()
    }

    override fun dependencies(): List<Class<out Initializer<*>>> {
        return emptyList()
    }
}
```

```
public class A{
    static A JUST_FOR_INIT = AppInitializer.getInstance(ContextShadow._ContextShadow).initializeComponent(AInitializer.class);

    public static void init(){
        // do some thing init
    }
}
```

**Comment by blipinsk** [comment]
I don't understand the purpose of this. `Initializers` from the app-startup library are initialized automatically when creating your `Application` instance. So when you have a UI component, `Application` instance should be available already and all Initializers initialized by then.

**Comment by BaskDuan** [comment]
Some custom UI like H5WebView should have init function. If init in Application may cost a lot of time (about 300ms), this way may be could init some UI like this to init? I don't know. I think static filed init is bad practice, but it's worked...

**Comment by blipinsk** [comment]
Ok, I think I get what you need. You basically want the initialized instance from the `Initializer`, the UI thing doesn't matter.

In general using `initializeComponent` is the right choice. It will give you the initialized component if it's already initialized, or initialize it if it's not ready (only if you'd specify `remove ` in the AndroidManifest).
But I wouldn't suggest using `static` field (I'd rather choose a lazy initialization), because static field initialization might come in conflict with the `Application` initialization order (e.g. if you've used an instance of `A` in the Application class etc.).

**Comment by blipinsk** [comment]
Closing as this is not directly related to the git repository. Feel free to post a question on StackOverflow if you need more help.
